# Spring profile = jpa
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/spring-boot-jpa-mappings-app-local-jpa?schema=public
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    enabled: false
