# Spring profile = jpa
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/spring-boot-jpa-mappings-app-local-jpa?schema=public
    username: postgres
    password: postgres@15
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 30
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    enabled: false
