# Spring Profile = liquibase
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/spring-boot-jpa-mappings-app-local-liquibase?schema=public
  # Liquibase configurations (ORMs must be compliant with Liquibase changelog specifications)
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:/db/liquibase/changelog-master.xml
