# Spring Profile = liquibase
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/spring-boot-jpa-mappings-app-local-liquibase?schema=public
    username: postgres
    password: postgres@15
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 30
      minimum-idle: 10
  # Liquibase configurations (ORMs must be compliant with Liquibase changelog specifications)
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:/db/liquibase/changelog-master.xml
